# Betting against beta

**AIM:** To make case for a defensive (also called betting-against-beta at times) stock strategy.

**INSTRUCTION:**
1. Using python and the data (NIFTY constituents, and their prices for the past 11 years) attached, generate monthly portfolios of top 10 stocks as per the defensive factor ranking logic, and compute the PNL.

2. Use a maximum of 12 months of lookback, so that you can have PNL performance for full 10 years. Show the performance stats you feel make sense.

3. Assume cash holding. Assume zero costs. Assume slippage free execution at closing price. So in effect all you need are spot prices which we have shared.

The calculation for beta is as follows:<br>

$$ \text{Beta coefficient} (\beta)=\frac{\text { Covariance }\left(R_{e}, R_{m}\right)}{\operatorname{Variance}\left(R_{m}\right)}$$<br>

where:<br>
$R_{e}=$ the return on an individual stock<br>
$R_{m}=$ the return on the overall market<br>
Covariance $=$ how changes in a stock's returns are
related to changes in the market's returns<br>
Variance $=$ how far the market's data points spread
out from their average value<br>

### Approach

1. Load data - nifty_constituents.csv, nifty_constituents_prices.csv, NIFTY 50_Data.csv
2. Define a function to identify stocks constituting Nifty at the 1st of every month beginning 1 Jan 2011.
    - Compute beta for all those stocks for a lookback period of 12 months.
    - Sort the stocks according to their beta in ascending order.
    - Return top 10 low beta stock names
3. Create a for loop for all months beginning Jan 2011 to Dec 2020.
    - Get top 10 Low beta stocks
    - Calculate daily and monthly returns assuming equal weighted investment in those 10 stocks.
4. Plots:
    - Daily PNL compared to Nifty 50
    - monthly PNL compared to Nifty 50
    - Yearly PNL compared to Nifty 50
5. Compute Stats - Sharpe ratio, Max drawdown, Alpha, etc.

In [40]:
import pandas as pd
import numpy as np
import plotly.express as px
import datetime
from dateutil.relativedelta import *

In [41]:
# Load data
nifty_constituents = pd.read_csv("nifty_constituents.csv", index_col = 'date')
nifty_constituents_prices = pd.read_csv("nifty_constituents_prices.csv", index_col= 'date')
nifty_50_data = pd.read_csv("NIFTY 50_Data.csv", index_col= 'Date')

In [72]:
nifty_constituents.index = pd.to_datetime(nifty_constituents.index)
nifty_constituents_prices.index = pd.to_datetime(nifty_constituents_prices.index)
nifty_50_data.index = pd.to_datetime(nifty_50_data.index)

In [42]:
def top10_low_beta_stocks(for_date):

SyntaxError: unexpected EOF while parsing (<ipython-input-42-e120a8968cf3>, line 2)

In [43]:
start_date = datetime.datetime(2011, 1, 1)
end_date = datetime.datetime(2020, 12, 31)

while start_date <= end_date:
    print(start_date)
    start_date += relativedelta(months=+1)

2011-01-01 00:00:00
2011-02-01 00:00:00
2011-03-01 00:00:00
2011-04-01 00:00:00
2011-05-01 00:00:00
2011-06-01 00:00:00
2011-07-01 00:00:00
2011-08-01 00:00:00
2011-09-01 00:00:00
2011-10-01 00:00:00
2011-11-01 00:00:00
2011-12-01 00:00:00
2012-01-01 00:00:00
2012-02-01 00:00:00
2012-03-01 00:00:00
2012-04-01 00:00:00
2012-05-01 00:00:00
2012-06-01 00:00:00
2012-07-01 00:00:00
2012-08-01 00:00:00
2012-09-01 00:00:00
2012-10-01 00:00:00
2012-11-01 00:00:00
2012-12-01 00:00:00
2013-01-01 00:00:00
2013-02-01 00:00:00
2013-03-01 00:00:00
2013-04-01 00:00:00
2013-05-01 00:00:00
2013-06-01 00:00:00
2013-07-01 00:00:00
2013-08-01 00:00:00
2013-09-01 00:00:00
2013-10-01 00:00:00
2013-11-01 00:00:00
2013-12-01 00:00:00
2014-01-01 00:00:00
2014-02-01 00:00:00
2014-03-01 00:00:00
2014-04-01 00:00:00
2014-05-01 00:00:00
2014-06-01 00:00:00
2014-07-01 00:00:00
2014-08-01 00:00:00
2014-09-01 00:00:00
2014-10-01 00:00:00
2014-11-01 00:00:00
2014-12-01 00:00:00
2015-01-01 00:00:00
2015-02-01 00:00:00
2015-03-01 00:00:00
2015-04-01 00:00:00
2015-05-01 00:00:00
2015-06-01 00:00:00
2015-07-01 00:00:00
2015-08-01 00:00:00
2015-09-01 00:00:00
2015-10-01 00:00:00
2015-11-01 00:00:00
2015-12-01 00:00:00
2016-01-01 00:00:00
2016-02-01 00:00:00
2016-03-01 00:00:00
2016-04-01 00:00:00
2016-05-01 00:00:00
2016-06-01 00:00:00
2016-07-01 00:00:00
2016-08-01 00:00:00
2016-09-01 00:00:00
2016-10-01 00:00:00
2016-11-01 00:00:00
2016-12-01 00:00:00
2017-01-01 00:00:00
2017-02-01 00:00:00
2017-03-01 00:00:00
2017-04-01 00:00:00
2017-05-01 00:00:00
2017-06-01 00:00:00
2017-07-01 00:00:00
2017-08-01 00:00:00
2017-09-01 00:00:00
2017-10-01 00:00:00
2017-11-01 00:00:00
2017-12-01 00:00:00
2018-01-01 00:00:00
2018-02-01 00:00:00
2018-03-01 00:00:00
2018-04-01 00:00:00
2018-05-01 00:00:00
2018-06-01 00:00:00
2018-07-01 00:00:00
2018-08-01 00:00:00
2018-09-01 00:00:00
2018-10-01 00:00:00
2018-11-01 00:00:00
2018-12-01 00:00:00
2019-01-01 00:00:00
2019-02-01 00:00:00
2019-03-01 00:00:00
2019-04-01 00:00:00
2019-05-01 00:00:00
2019-06-01 00:00:00
2019-07-01 00:00:00
2019-08-01 00:00:00
2019-09-01 00:00:00
2019-10-01 00:00:00
2019-11-01 00:00:00
2019-12-01 00:00:00
2020-01-01 00:00:00
2020-02-01 00:00:00
2020-03-01 00:00:00
2020-04-01 00:00:00
2020-05-01 00:00:00
2020-06-01 00:00:00
2020-07-01 00:00:00
2020-08-01 00:00:00
2020-09-01 00:00:00
2020-10-01 00:00:00
2020-11-01 00:00:00
2020-12-01 00:00:00

In [55]:
start_date = datetime.datetime(2011, 2, 1)
nifty_constituents.index = pd.to_datetime(nifty_constituents.index)
nifty_constituents.loc[start_date]

ABB               0
ACC               1
ADANIPORTS        0
AMBUJACEM         1
ASIANPAINT        0
               ...
WIPRO             1
YESBANK           0
ZEEL              0
month             2
month_start    True
Name: 2011-02-01 00:00:00, Length: 87, dtype: object

In [45]:
nifty_constituents

,ABB,ACC,ADANIPORTS,AMBUJACEM,ASIANPAINT,AUROPHARMA,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,...,TCS,TECHM,TITAN,ULTRACEMCO,UNITECH,UPL,VEDL,WIPRO,YESBANK,ZEEL
date,,,,,,,,,,,,,,,,,,,,,
2009-12-31,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2010-01-04,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2010-01-05,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2010-01-06,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2010-01-07,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-27,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2020-12-28,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2020-12-29,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2020-12-30,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2020-12-31,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0

In [46]:
df = nifty_constituents
df["month"] = (pd.to_datetime(df.index)).month
df["month_start"] = ~df.month.eq(df.month.shift(1))

In [47]:
mask = df[df.month_start == True]

In [48]:
nifty_month_start = mask[1:]
nifty_month_start

,ABB,ACC,ADANIPORTS,AMBUJACEM,ASIANPAINT,AUROPHARMA,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,...,TITAN,ULTRACEMCO,UNITECH,UPL,VEDL,WIPRO,YESBANK,ZEEL,month,month_start
date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1,True
2010-02-01,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2,True
2010-03-02,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3,True
2010-04-01,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4,True
2010-05-03,1.0,1.0,0.0,1.0,0.0,0.0,1,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-01,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,8,True
2020-09-01,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,9,True
2020-10-01,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,10,True
2020-11-01,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,11,True
2020-12-01,0.0,0.0,1.0,0.0,1.0,0.0,1,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,12,True

In [77]:
# Daily returns of all the stocks
daily_returns = nifty_constituents_prices.apply(lambda row: row.pct_change(), axis=0)

In [58]:
nifty_50_data["daily_return"] = nifty_50_data.Close.pct_change()

In [51]:
def compute_beta(stock, current_date, lookback_period=12):
    start_date = current_date - relativedelta(months=12)
    nifty_returns_array = np.array(nifty_50_data.loc[start_date: current_date].daily_return.to_list())
    stock_return_array = np.array(daily_returns.loc[start_date: current_date][stock].to_list())
    beta = np.cov(stock_return_array, nifty_returns_array)[0, 1]/np.var(nifty_returns_array)
    return beta

SyntaxError: unexpected EOF while parsing (<ipython-input-51-e8b5ac903b1c>, line 3)

In [86]:
current_date = datetime.datetime(2011, 2, 1)
start_date = current_date - relativedelta(months=12)
stock = "ACC"
x = np.array(nifty_50_data.loc[start_date: current_date].daily_return.to_list())
y = np.array(daily_returns.loc[start_date: current_date][stock].to_list())
np.cov(y, x)[0,1]/np.var(x)

0.6463952788771729

In [79]:
nifty_constituents_prices.columns

Index(['ABB', 'ACC', 'ADANIPORTS', 'AMBUJACEM', 'ASIANPAINT', 'AUROPHARMA',
       'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BANKBARODA',
       'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CAIRN', 'CIPLA',
       'COALINDIA', 'DIVISLAB', 'DLF', 'DRREDDY', 'EICHERMOT', 'GAIL',
       'GRASIM', 'HCLTECH', 'HDFC', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO',
       'HINDALCO', 'HINDPETRO', 'HINDUNILVR', 'IBULHSGFIN', 'ICICIBANK',
       'IDEA', 'IDFC', 'INDUSINDBK', 'INDUSTOWER', 'INFY', 'IOC', 'ITC',
       'JINDALSTEL', 'JPASSOCIAT', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'LUPIN',
       'M&M', 'MARUTI', 'MCDOWELL-N', 'NESTLEIND', 'NMDC', 'NTPC', 'ONGC',
       'PNB', 'POWERGRID', 'RANBAXY', 'RCOM', 'RELCAPITAL', 'RELIANCE',
       'RELINFRA', 'RPOWER', 'SAIL', 'SBILIFE', 'SBIN', 'SHREECEM', 'SIEMENS',
       'STER', 'SUNPHARMA', 'SUZLON', 'TATAMOTORS', 'TATAMTRDVR', 'TATAPOWER',
       'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'ULTRACEMCO', 'UNITECH', 'UPL',
       'VEDL', 'WIPRO', 'YESBANK', 'ZEEL'],
      dtype='object')